# Generated by Django 4.2.2 on 2023-08-11 17:04

import accounts.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Это поле предназначено для изображения профиля пользователя. Картинка должна быть Х на Х.', null=True, upload_to='profile/', verbose_name='Фотография')),
                ('phone', models.CharField(blank=True, help_text='Поле для хранения номера телефона пользователя. Уникальное, с возможностью валидации.', max_length=20, null=True, unique=True, validators=[accounts.utils.validate_phone_number], verbose_name='Номер телефона')),
                ('birth_date', models.DateField(blank=True, help_text='Поле для хранения даты рождения пользователя.', null=True, verbose_name='Дата рождения')),
                ('about', models.TextField(blank=True, help_text='Текстовое поле для краткой информации о пользователе, ограниченное 200 символами.', max_length=200, null=True, verbose_name='Обо мне')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания профиля, автоматически устанавливаемые при создании новой записи.', verbose_name='Дата создания')),
                ('user', models.OneToOneField(help_text="Поле связи 'один к одному' с моделью пользователя Django.", on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
                'ordering': ['-created_at'],
            },
        ),
    ]
