# Generated by Django 4.2.2 on 2023-09-06 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule_of_road_transport',
            options={'ordering': ['-created_at'], 'verbose_name': 'График автоперевозок', 'verbose_name_plural': 'График автоперевозок'},
        ),
        migrations.AddField(
            model_name='schedule_of_road_transport',
            name='file_and_photo',
            field=models.FileField(blank=True, help_text='Загрузите PDF или изображение (IMG) документа, содержащего информацию о графике дорожного транспорта. Разрешены файлы в форматах PDF или изображений (например, JPG, PNG).', null=True, upload_to='Schedule_of_road_transport_documents/', verbose_name='PDF или IMG документ'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='additional_info',
            field=models.TextField(blank=True, help_text='Любая дополнительная информация, которую следует учитывать при отправке или доставке.', null=True, verbose_name='Дополнительная информация'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='address_line',
            field=models.TextField(help_text='Указывается адрес, откуда будет забираться груз.', verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='company_name',
            field=models.CharField(blank=True, help_text='Название компании отправителя. Например, "Remalux".', max_length=255, null=True, verbose_name='Наименование компании'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='customs_clearance',
            field=models.BooleanField(default=False, help_text='Отметьте, если груз требует таможенного оформления.', verbose_name='Таможенное оформление'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='delivery_address',
            field=models.TextField(help_text='Адрес, куда груз будет доставлен.', verbose_name='Доставка'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='delivery_deadline',
            field=models.DateField(blank=True, help_text='Желаемая дата доставки груза.', null=True, verbose_name='Сроки доставки'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='desired_departure_date',
            field=models.DateField(help_text='Дата, когда отправитель хочет, чтобы груз был отправлен.', verbose_name='Желаемая дата отправления'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='document',
            field=models.FileField(blank=True, help_text='Здесь можно загрузить документацию или иную важную информацию, связанную с грузом.', null=True, upload_to='cargo_documents/', verbose_name='PDF документ'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='email',
            field=models.EmailField(help_text='Электронный адрес отправителя для уведомлений или связи.', max_length=254, verbose_name='Адрес электронной почты'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='full_name',
            field=models.CharField(help_text='Имя отправителя или контактного лица. Например, "Marselle".', max_length=255, verbose_name='Полное имя'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='insurance_needed',
            field=models.CharField(choices=[('yes', 'Да'), ('no', 'Нет')], default='Нет', help_text='Выберите "Да", если груз нуждается в страховании, и "Нет", если нет.', max_length=3, verbose_name='Необходимость страхования груза'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='packaging',
            field=models.BooleanField(default=False, help_text='Отметьте, если необходимо особое упаковывание груза.', verbose_name='Упаковка'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='phone_number',
            field=models.CharField(help_text='Телефон для связи. Например, "+7747***9991".', max_length=20, verbose_name='Контактный номер телефона'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='product_name',
            field=models.CharField(help_text="Здесь вводится наименование товара или продукта, который будет отправлен. В нашем примере это 'Краска Мемби'.", max_length=255, verbose_name='Наименование товара'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, help_text='Общее количество товара или продукта. Например, "100" банок краски.', null=True, verbose_name='Количество единиц товара'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='special_requirements',
            field=models.TextField(blank=True, help_text='Любые дополнительные требования или заметки к грузу.', null=True, verbose_name='Особые требования'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='storage',
            field=models.BooleanField(default=False, help_text='Отметьте, если необходимо временное хранение груза перед отправкой или после доставки.', verbose_name='Необходимость хранения'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='volume',
            field=models.FloatField(blank=True, help_text='Здесь указывается объем груза в кубических метрах или другой единице измерения. Например, "2" может быть 2 куб. м.', null=True, verbose_name='Объем груза'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='weight',
            field=models.FloatField(help_text="Указывается вес груза, который отправляется. Например, '2' может означать 2 кг.", verbose_name='Вес груза'),
        ),
        migrations.AlterField(
            model_name='support',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Дата и время, когда обращение было создано.', verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='support',
            name='email',
            field=models.EmailField(help_text='Введите адрес вашей электронной почты, чтобы мы могли связаться с вами.', max_length=254, verbose_name='Адрес электронной почты'),
        ),
        migrations.AlterField(
            model_name='support',
            name='message',
            field=models.TextField(help_text='Опишите вашу проблему или вопрос. Максимальная длина сообщения - 1000 символов.', max_length=1000, verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='support',
            name='name',
            field=models.CharField(help_text='Введите ваше полное имя.', max_length=100, verbose_name='Имя'),
        ),
    ]
